"""
    Contain constains variable
"""
# Data
TRAIN_DIR = "DUC_TEXT/train/"
TEST_DIR = "DUC_TEXT/test/"
EXPECTED_SUM_DIR = "DUC_SUM/"

# Actual output
OUTPUT_BOW_DIR = "OUTPUT/BOW/"
OUTPUT_TF_IDF_DIR = "OUTPUT/TF_IDF/"
OUTPUT_WORD2VEC_DIR = "OUTPUT/WORD2VEC/"

# Test
TEST_BOW_DIR = "TEST/BOW/"
TEST_TF_IDF_DIR = "TEST/TF_IDF/"
TEST_WORD2VEC_DIR = "TEST/WORD2VEC/"
